version: "3.7"

networks:
  api_network:

services:
  api:
    image: tomcat:9.0.35-jdk11-corretto
    command: sh -c "catalina.sh run"
    ports:
      - 8888:8080
    volumes:
      - ./webservices/:/usr/local/tomcat/webapps/
    networks:
      api_network: